### ISSUE TITLE
Error setting up platform legacy

### ISSUE THREAD

**Issue by trommegutten** [dels78/home-assistant-device_tracker.edgeos#2]
I have
- renamed the file edgeos.py to device_tracker.py
- added '__init__.py' file in folder

But I'm getting an error. I'm using Home Assistant 0.98.1

This is the error log:
```
Error setting up platform legacy
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/device_tracker/setup.py", line 65, in async_setup_legacy
    self.platform.get_scanner, hass, {DOMAIN: self.config}
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/homeassistant/custom_components/edgeos/device_tracker.py", line 71, in get_scanner
    scanner = EdgeOSDeviceScanner(config[DOMAIN])
  File "/home/hass/homeassistant/custom_components/edgeos/device_tracker.py", line 118, in __init__
    data = self.get_edgeos_data()
  File "/home/hass/homeassistant/custom_components/edgeos/device_tracker.py", line 155, in get_edgeos_data
    devices.update(self._get_arp())
  File "/home/hass/homeassistant/custom_components/edgeos/device_tracker.py", line 182, in _get_arp
    lines = self.connection.run_command(_ARP_CMD)
  File "/home/hass/homeassistant/custom_components/edgeos/device_tracker.py", line 232, in run_command
    from pexpect import pxssh, exceptions
ModuleNotFoundError: No module named 'pexpect'
```

Have You done anything else with the code to make it work?

**Comment by manuel-jrs** [comment]
I have the same problem. Did you resolve it?

**Comment by ysjiang4869** [comment]
I solve this problem.
the folder info:
```
- custom_components/edgeos
  - __init__.py
  - device_tracker.py
  - manifest.json
 ```
in manifest
```{
  "domain": "edgeos",
  "name": "EdgeOS Device Tracker",
  "documentation": "https://example.com",
  "dependencies": [],
  "codeowners": ["@your-github-username"],
  "requirements": [],
  "homeassistant": "2023.12.0",
  "version":"1.0.0",
  "integration_type": "virtual",
  "supported_by": "device_tracker"
}

```

**Comment by dels78** [comment]
happy to merge any PR you guys send, as mentioned before, I am no longer using this device!
